### ISSUE TITLE
**FINAL WARNING**

### ISSUE THREAD

**Issue by MattReal6833** [veduislive/Hostactyl#1]
Hey Veduilive.
Me and another colleuge of mine have warned you that you must add credits to the license or somewhere stating it's based off dashactyl. You have 24 hours to make this right before the owners of dashactyl file a DMCA report against you. Did you know that copying open source projects which have a license and not giving them any credit is against multiple country laws? This can get you into legal trouble. We're not trying to stop you from developing Hostactyl, we just want the folks to know that it's based off dashactyl. I repeat, you have 24 hours before a DMCA will be filed against you.

Thanks
 from the developers/owners of Votion Dev (Owners of dashactyl)

**Comment by MattReal6833** [comment]
Oh yeah, and proof that this is dashactyl: 
![image](https://user-images.githubusercontent.com/56598575/155992212-dd44c358-53eb-48fb-a0ab-7db2e6192328.png)

**Comment by veduislive** [comment]
mee The official owner of hostactyl has terminated this projest and will not repete this in future!
